sylius_resource:
    resources:
        app.newsletter:
            driver: doctrine/orm
            classes:
                model: App\Entity\Newsletter
                repository: App\Repository\NewsletterRepository
                form: App\Form\Type\NewsletterType
